### ISSUE TITLE
problem with running the widget for the first time

### ISSUE THREAD

**Issue by IdoSagiv** [tyichye/daily-calendar-clock-widget#20]
Hey,
I installed the widget on my phone (one plus 6) as you instructed on the "Project installation" section in the README.
I have noticed that the widget fails to respond after first calendar permissions are granted, and in order to make it work you need to remove the widget (all its instances - it doesn't work otherwise) from the home screen and re-add it.
I tried removing the permissions and adding the widget multiple times and the bug repeated itself each time.
I suggest that until you fix this, you open a Q&A page to the repository and add my problem with the presented solution.
If you will accept my suggestion, I would like to later open a pull request in order to update the README file to link to this Q&A section.

Ido

**Comment by tyichye** [comment]
Hi,
Thank you for your report.
We pushed a new version after fixing the bug. please let us know if everything working properly now.

**Comment by IdoSagiv** [comment]
Works perfectly! Thanks!
